# Generated by Django 4.1 on 2022-08-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_npo_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='npo',
            name='website',
            field=models.URLField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
