# Generated by Django 4.1 on 2022-08-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_npo_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npo',
            name='website',
            field=models.URLField(max_length=500),
        ),
    ]
