# Generated by Django 4.1 on 2022-08-10 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_npo_description_alter_npo_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('npo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.npo')),
            ],
        ),
    ]
